export const imageMap = {
  "iPhone 14": "/Assets/products/iphone-14.jpg",
  "Samsung Galaxy S23": "/Assets/products/samsung-galaxy-s23.jpg",
  "Sony WH-1000XM4": "/Assets/products/sony-wh-1000xm4.jpg",
  "Dell XPS 13 Laptop": "/Assets/products/dell-xps-13.jpg",
  "Apple iPad Air": "/Assets/products/ipad-air.jpg",
  "Nike Air Max": "/Assets/products/nike-air-max.jpg",
  "Adidas Hoodie": "/Assets/products/adidas-hoodie.jpg",
  "Levi's Jeans": "/Assets/products/levis-jeans.jpg",
  "Puma T-Shirt": "/Assets/products/puma-tshirt.jpg",
  "Zara Jacket": "/Assets/products/zara-jacket.jpg",
  "Atomic Habits": "/Assets/products/atomic-habits.jpg",
  "The Lean Startup": "/Assets/products/lean-startup.jpg",
  "Rich Dad Poor Dad": "/Assets/products/rich-dad-poor-dad.jpg",
  "The Alchemist": "/Assets/products/the-alchemist.jpg",
  "Clean Code": "/Assets/products/clean-code.jpg",
  "Fossil Watch": "/Assets/products/fossil-watch.jpg",
  "Ray-Ban Sunglasses": "/Assets/products/rayban-sunglasses.jpg",
  "Wildcraft Backpack": "/Assets/products/wildcraft-backpack.jpg",
  "Noise Smartwatch": "/Assets/products/noise-smartwatch.jpg",
  "Boat Earbuds": "/Assets/products/boat-earbuds.jpg",
  "Ikea Study Table": "/Assets/products/study-table.jpg",
  "Urban Ladder Sofa": "/Assets/products/sofa.jpg",
  "Nilkamal Chair": "/Assets/products/chair.jpg",
  "Wakefit Mattress": "/Assets/products/mattress.jpg",
  "Bookshelf": "/Assets/products/bookshelf.jpg",
};
